export type MyntraPgFieldType = 'string' | 'number' | 'date';

export type MyntraPgFieldDefinition = {
  key: string;
  type: MyntraPgFieldType;
  aliases?: string[];
};

/** Minimum header groups for Myntra PG Reverse Settled report. */
export const MYNTRA_PG_REVERSE_REQUIRED_HEADER_GROUPS = [
  ['order_release_id', 'Order Release ID', 'order release id'],
  ['order_line_id', 'Order Line ID', 'order line id'],
  ['return_type', 'Return Type', 'return type'],
  ['return_date', 'Return Date', 'return date'],
] as const;

/** Dynamic per-day settlement amount columns (e.g. Settlement_on_2026_03_02). */
export const MYNTRA_PG_SETTLEMENT_COLUMN_KEY_PATTERN =
  /^settlement_on_|^settlementon/i;

/**
 * Known PG Reverse Settled export columns (snake_case keys after header normalization).
 * All values are stored in rowData; key fields are also promoted to top-level document props.
 */
export const MYNTRA_PG_REVERSE_FIELD_CATALOG: MyntraPgFieldDefinition[] = [
  { key: 'order_release_id', type: 'string' },
  { key: 'order_line_id', type: 'string' },
  { key: 'return_type', type: 'string' },
  { key: 'return_date', type: 'date' },
  { key: 'packing_date', type: 'date' },
  { key: 'delivery_date', type: 'date' },
  { key: 'ecommerce_portal_name', type: 'string' },
  { key: 'sku_code', type: 'string' },
  { key: 'invoice_number', type: 'string' },
  { key: 'packet_id', type: 'string' },
  { key: 'hsn_code', type: 'string' },
  { key: 'product_tax_category', type: 'string' },
  { key: 'currency', type: 'string' },
  { key: 'seller_product_amount', type: 'number' },
  { key: 'postpaid_amount', type: 'number' },
  { key: 'prepaid_amount', type: 'number' },
  { key: 'mrp', type: 'number' },
  { key: 'total_discount_amount', type: 'number' },
  { key: 'shipping_case_s', type: 'string' },
  { key: 'total_tax_rate', type: 'number' },
  { key: 'igst_amount', type: 'number' },
  { key: 'cgst_amount', type: 'number' },
  { key: 'sgst_amount', type: 'number' },
  { key: 'tcs_amount', type: 'number' },
  { key: 'tds_amount', type: 'number' },
  { key: 'commission_percentage', type: 'number' },
  { key: 'minimum_commission', type: 'number' },
  { key: 'platform_fees', type: 'number' },
  { key: 'total_commission', type: 'number' },
  { key: 'total_commission_plus_tcs_tds_deduction', type: 'number' },
  { key: 'total_logistics_deduction', type: 'number' },
  { key: 'shipping_fee', type: 'number' },
  { key: 'fixed_fee', type: 'number' },
  { key: 'pick_and_pack_fee', type: 'number' },
  { key: 'payment_gateway_fee', type: 'number' },
  { key: 'total_tax_on_logistics', type: 'number' },
  { key: 'article_level', type: 'string' },
  { key: 'shipment_zone_classification', type: 'string' },
  { key: 'customer_paid_amt', type: 'number' },
  { key: 'total_settlement', type: 'number' },
  { key: 'total_actual_settlement', type: 'number' },
  { key: 'amount_pending_settlement', type: 'number' },
  { key: 'prepaid_commission_deduction', type: 'number' },
  { key: 'prepaid_logistics_deduction', type: 'number' },
  { key: 'prepaid_payment', type: 'number' },
  { key: 'postpaid_commission_deduction', type: 'number' },
  { key: 'postpaid_logistics_deduction', type: 'number' },
  { key: 'postpaid_payment', type: 'number' },
  { key: 'settlement_date_prepaid_comm_deduction', type: 'date' },
  { key: 'settlement_date_prepaid_logistics_deduction', type: 'date' },
  { key: 'settlement_date_prepaid_payment', type: 'date' },
  { key: 'settlement_date_postpaid_comm_deduction', type: 'date' },
  { key: 'settlement_date_postpaid_logistics_deduction', type: 'date' },
  { key: 'settlement_date_postpaid_payment', type: 'date' },
  { key: 'bank_utr_no_prepaid_comm_deduction', type: 'string' },
  { key: 'bank_utr_no_prepaid_logistics_deduction', type: 'string' },
  { key: 'bank_utr_no_prepaid_payment', type: 'string' },
  { key: 'bank_utr_no_postpaid_comm_deduction', type: 'string' },
  { key: 'bank_utr_no_postpaid_logistics_deduction', type: 'string' },
  { key: 'bank_utr_no_postpaid_payment', type: 'string' },
  { key: 'postpaid_amount_other', type: 'number' },
  { key: 'prepaid_amount_other', type: 'number' },
  { key: 'shipping_amount', type: 'number' },
  { key: 'gift_amount', type: 'number' },
  { key: 'additional_amount', type: 'number' },
  { key: 'cess_amount', type: 'number' },
  { key: 'taxable_amount', type: 'number' },
  { key: 'igst_rate', type: 'number' },
  { key: 'cgst_rate', type: 'number' },
  { key: 'sgst_rate', type: 'number' },
  { key: 'cess_rate', type: 'number' },
  { key: 'tcs_igst_rate', type: 'number' },
  { key: 'tcs_sgst_rate', type: 'number' },
  { key: 'tcs_cgst_rate', type: 'number' },
  { key: 'tds_rate', type: 'number' },
  { key: 'brand', type: 'string' },
  { key: 'gender', type: 'string' },
  { key: 'brand_type', type: 'string' },
  { key: 'article_type', type: 'string' },
  { key: 'supply_type', type: 'string' },
  { key: 'try_and_buy_purchase', type: 'string' },
  { key: 'customer_name', type: 'string' },
  { key: 'customer_delivery_pin_code', type: 'string' },
  { key: 'seller_gstn', type: 'string' },
  { key: 'seller_name', type: 'string' },
  { key: 'myntra_gstn', type: 'string' },
  { key: 'shipping_city', type: 'string' },
  { key: 'shipping_pin_code', type: 'string' },
  { key: 'shipping_state', type: 'string' },
  { key: 'shipping_state_code', type: 'string' },
  { key: 'prepaid_commission_percentage', type: 'number' },
  { key: 'prepaid_minimum_commission', type: 'number' },
  { key: 'prepaid_platform_fees', type: 'number' },
  { key: 'prepaid_total_commission', type: 'number' },
  { key: 'prepaid_ship_commission_charge', type: 'number' },
  { key: 'prepaid_gift_commission_charge', type: 'number' },
  { key: 'prepaid_cod_commission_charge', type: 'number' },
  { key: 'prepaid_cart_discount', type: 'number' },
  { key: 'prepaid_coupon_discount', type: 'number' },
  { key: 'postpaid_commission_percentage', type: 'number' },
  { key: 'postpaid_minimum_commission', type: 'number' },
  { key: 'postpaid_platform_fees', type: 'number' },
  { key: 'postpaid_total_commission', type: 'number' },
  { key: 'postpaid_ship_commission_charge', type: 'number' },
  { key: 'postpaid_gift_commission_charge', type: 'number' },
  { key: 'postpaid_cod_commission_charge', type: 'number' },
  { key: 'postpaid_cart_discount', type: 'number' },
  { key: 'postpaid_coupon_discount', type: 'number' },
  { key: 'seller_order_id', type: 'string' },
  { key: 'return_id', type: 'string' },
  { key: 'tcs_amount_prepaid', type: 'number' },
  { key: 'tcs_amount_postpaid', type: 'number' },
  { key: 'tds_amount_prepaid', type: 'number' },
  { key: 'tds_amount_postpaid', type: 'number' },
  { key: 'seller_tier', type: 'string' },
  {
    key: 'royaltycharges_prepaid',
    type: 'number',
    aliases: ['royaltyCharges_prepaid', 'RoyaltyCharges_prepaid'],
  },
  {
    key: 'royaltycharges_postpaid',
    type: 'number',
    aliases: ['royaltyCharges_postpaid', 'RoyaltyCharges_postpaid'],
  },
  {
    key: 'royaltypercent_prepaid',
    type: 'number',
    aliases: ['royaltyPercent_prepaid', 'RoyaltyPercent_prepaid'],
  },
  {
    key: 'royaltypercent_postpaid',
    type: 'number',
    aliases: ['royaltyPercent_postpaid', 'RoyaltyPercent_postpaid'],
  },
  {
    key: 'marketingcharges_prepaid',
    type: 'number',
    aliases: ['marketingCharges_prepaid', 'MarketingCharges_prepaid'],
  },
  {
    key: 'marketingcharges_postpaid',
    type: 'number',
    aliases: ['marketingCharges_postpaid', 'MarketingCharges_postpaid'],
  },
  {
    key: 'marketingpercent_prepaid',
    type: 'number',
    aliases: ['marketingPercent_prepaid', 'MarketingPercent_prepaid'],
  },
  {
    key: 'marketingpercent_postpaid',
    type: 'number',
    aliases: ['marketingPercent_postpaid', 'MarketingPercent_postpaid'],
  },
  {
    key: 'marketingcontribution_prepaid',
    type: 'number',
    aliases: ['marketingContribution_prepaid', 'MarketingContribution_prepaid'],
  },
  {
    key: 'marketingcontribution_postpaid',
    type: 'number',
    aliases: ['marketingContribution_postpaid', 'MarketingContribution_postpaid'],
  },
  {
    key: 'reverseadditionalcharges_prepaid',
    type: 'number',
    aliases: ['reverseAdditionalCharges_prepaid', 'ReverseAdditionalCharges_prepaid'],
  },
  {
    key: 'reverseadditionalcharges_postpaid',
    type: 'number',
    aliases: ['reverseAdditionalCharges_postpaid', 'ReverseAdditionalCharges_postpaid'],
  },
  { key: 'commission_discount', type: 'number' },
  { key: 'sjit_incentive_amount', type: 'number' },
  { key: 'commission_base_amount', type: 'number' },
  { key: 'commission_tax_amount', type: 'number' },
];
