name: Backend PROD Deploy

on:
  push:
    branches:
      - ecommreco_prod

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend PROD
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "===== BACKEND PROD ====="

            cd /home/ubuntu/ecommreco_prod/ecommreco-backend

            git fetch origin
            git checkout ecommreco_prod
            git reset --hard origin/ecommreco_prod

            npm install

            npm run build

            pm2 restart api-prod

            pm2 save

            echo "Backend PROD deployed."