name: Frontend PROD Deploy

on:
  push:
    branches:
      - ecommreco_prod

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend PROD
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "===== FRONTEND PROD ====="

            cd /home/ubuntu/ecommreco_prod/ecommreco-frontend

            git fetch origin
            git checkout ecommreco_prod
            git reset --hard origin/ecommreco_prod

            npm install

            npm run build:production

            sudo systemctl reload nginx

            echo "Frontend PROD deployed."